id = "ehir-zed-lsp"
name = "EHIR LSP Server"
version = "0.0.1"
schema_version = 1
authors = ["Maksim Shushkevich <m.e.shushkevich@yandex.com>"]
description = "LSP server for EHIR"
repository = "https://github.com/meshushkevich/ehir-zed-lsp"


[language_servers.ehir]
name = "EHIR Language Server"
language = "EHIR"


[grammars.ehir]
repository = "https://github.com/meshushkevich/tree-sitter-ehir"
commit = "4b439b26fbf2a165b2cf996301c0b3f0dd543a12"
